name: Deploy to EC2

on:
  push:
    branches:
      - release/prod 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run commands on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@44.202.24.142 << 'EOF'
            echo "Starting deployment..."
            cd /home/ubuntu/sumit && ls 
            echo "Deployment finished."
          EOF
